server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8

spring:
     # REDIS (RedisProperties)
     # Redis数据库索引（默认为0）
    redis:
         database: 0
     # Redis服务器地址
         host: 127.0.0.1
     # Redis服务器连接端口
         port: 6379
     # Redis服务器连接密码（默认为空）
         password:
     # 连接池最大连接数（使用负值表示没有限制）
         timeout: 100000

         jedis:
             pool:
                  max-wait: 1000ms
                 #最小空闲数量
                  min-idle: 1
                 #最大空闲数量
                  max-idle: 10
                 #最大连接数量
                  max-active: 1000
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/read
        username: root
        password: lvhaizhen1987
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.sea.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


